### ISSUE TITLE
504 timeout (nginx/php) - pm.max_children

### ISSUE THREAD

**Issue by cgKAF** [YunoHost-Apps/streams_ynh#29]
### Describe the bug

Also posted [here in the Yunohost forum](https://forum.yunohost.org/t/streams-504-timeout-nginx-running-out-of-children/28203)

Similar to, but not quite the same as [this issue already posted](https://github.com/YunoHost-Apps/streams_ynh/issues/27). Brand new install of Streams on a new subdomain. Worked like a dream for a couple of hours, then load times started freezing up and resulted in a 504 timeout (nginx) that lasted from between 15 minutes to all day.

To cut a long story short, I've [got around the issue](https://forum.yunohost.org/t/streams-504-timeout-nginx-running-out-of-children/28203/9?u=cgkaf) by editing the children and servers values in my `/etc/php/8.2/fpm/pool.d/streams.conf` config file, but I don't know if this is recommended.

I have been checking my free disk space and RAM with `dh -f` and `free -h` and both remain constant throughout.

### Context

**Hardware**: Lenovo ThinkCentre m720q, 8GB RAM (around 5GB free at the moment)
**YunoHost version**: 11.2.9.1 (stable)
**I have access to my server** : Through SSH and through the webadmin
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no
**If your request is related to an app, specify its name and version**: Streams 23.12.17~ynh1

### Steps to reproduce

Install Streams via web-admin, start federating & connecting with other profiles... then wait :)
No problems seemed to occur until my instance started federating with others.

### Expected behavior

Smooth, seamless browsing, with no errors in the log.

### Logs

On default settings, my `/var/log/php8.2-fpm.log` file gave this as sample output -- I had no errors up until a couple of hours of use:

```
[23-Jan-2024 21:29:01] NOTICE: fpm is running, pid 681
[23-Jan-2024 21:29:01] NOTICE: ready to handle connections
[23-Jan-2024 21:29:01] NOTICE: systemd monitor interval set to 10000ms
[23-Jan-2024 21:34:00] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 2 idle, and 12 total children
[23-Jan-2024 21:34:01] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 16 children, there are 1 idle, and 14 total children
[23-Jan-2024 21:34:02] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 3 idle, and 17 total children
[23-Jan-2024 21:34:03] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 3 idle, and 18 total children
[23-Jan-2024 21:34:04] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 19 total children
[23-Jan-2024 21:34:05] WARNING: [pool streams] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 23 total children
[23-Jan-2024 21:34:06] WARNING: [pool streams] server reached pm.max_children setting (24), consider raising it
```
After [modifying my config file](https://forum.yunohost.org/t/streams-504-timeout-nginx-running-out-of-children/28203/9?u=cgkaf), typical output now shows the "busy" error still occurring but not as frequently, and the "reached max children" error occurred once in the last ~10 or so hours. My site has not (as far as I know) frozen since.

**Comment by dragondaddy** [comment]
OK, so the good news is that it's perfectly safe to edit `/etc/php/8.2/fpm/pool.d/streams.conf` as long as you know what you're doing. The only thing to remember is that each time there'll be a package update, you will probably have to re-edit it to put your custom settings.

Luckily this package is designed in a way that it will not require frequent updates, as the application code itself is handled  using git commands directly (rather than through package updates).

As for the exact origin of the problem, I'm sorry to confess that I can't tell you exactly what happens here. I know I've had issues with my own server one day when someone with thousands of followers shared one of my post. The VPS I had when it happened was a rather tiny one (2GB RAM if I'm not mistaken) and got stuck a few hours.

Anyhow, I don't think that this issue could be solved by changing something in the YunoHost package. If you ever face a similar problem again, maybe the upstream repo would be a better place to open an issue, or you could discuss this on the Streams support group.

Do you think I can close this issue, or would you rather keep it open a while, see if anyone has any suggestions on how to handle your problem?

**Comment by cgKAF** [comment]
Thank you for the reply :)  Keep it open awhile -- I'd like to ask on the Streams support forum and see what they say there. Even if it's just a "yes, we know it's a problem", that's something that I can at least report back here.

**Comment by cgKAF** [comment]
By chance, a few minutes before I left here to try asking there, [someone else had asked](https://fediversity.site/display/?mid=https://fediversity.site/item/bf7acff8-3e36-4249-a133-dc46c0dc57c5&owt=8f92b208f68f57026ef75ace62dc866b) about more or less the same problem.

The replies say it's an issue common to most PHP-based Fedi software, and tweaking the max children settings in the config file is the workaround.

**Comment by dragondaddy** [comment]
Yeah, I saw that. Best answer ever about the values to choose.

_You slowly increase them until the problem goes away or your server complains._

**Comment by dragondaddy** [comment]
Closing as this is related to the app itself and not the YunoHost package.
